### ISSUE TITLE
[SWARM] service endpoint-mode=dnsrr support

### ISSUE THREAD

**Issue by Mararok** [docker-flow/docker-flow-proxy#13]
It would be great if you could implement it in the project :)

I checked some solution and dnsrr mode is working with haproxy "server-template" future very well.
Here is my custom backend template: 
```
{{range $sd := .ServiceDest}}
    backend {{$.AclName}}-be{{.Port}}_{{.Index}}
    mode http
    balance roundrobin
    server-template {{$.ServiceName}} 1-10 {{$.ServiceName}}:{{.Port}}  check resolvers docker
{{end}}
```

I hardcoded servers(1-10) because I didn't find any template var with number of replicas.

**Comment by vfarcic** [comment]
I created a new releases for the POC (`dockerflow/docker-flow-proxy:18.05.06-44`) but I didn't have time to test it properly. Can you please give it a try and let me know if you discover any issues? All you'll have to do is add `com.df.discoveryType=DNS` to the service.

**Comment by Mararok** [comment]
I found 1 bug when proxy instance started and envvar LISTENER_ADDRESS is sets then server-template is generated with 0 servers

**Comment by Mararok** [comment]
I found :) 
haproxy in version 1.8 supports something called EDNS https://www.haproxy.com/blog/dns-service-discovery-haproxy/ and with option http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.3.2-accepted_payload_size we can read more dns entries.

**Comment by jaschaio** [comment]
@Mararok Thanks for notifying me in slack about this :)

I asked this question as well in the haproxy forum an got the Following answer which seems logical as well:

> Well, either you set multiple server line with the same name:
> ```
> backend myapp
> […]
> server s1 myapp.domain.com:80 check resolvers mydns
> server s2 myapp.domain.com:80 check resolvers mydns
> server s3 myapp.domain.com:80 check resolvers mydns
> ```
> 
> Or you use server-template directive:
> 
> ```
> backend myapp
> […]
> server s 3 myapp.domain.com:80 check resolvers mydns
> ```
> 
> Adjust the number of servers to your need.
> 
> In each case, the resolvers should turn on one server per IP found in the response.

Anyway I will give the newest release a try tomorrow and report here

**Comment by jaschaio** [comment]
Getting these errors when adding the `com.df.discoveryType=DNS` label:

```
2018-05-11T06:04:21.184284915Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | [ALERT] 130/060421 (558) : Fatal errors found in configuration.
2018-05-11T06:04:22.187764322Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | [ALERT] 130/060422 (559) : parsing [/cfg/haproxy.cfg:88] : Wrong server-template number or range arg '0'.
2018-05-11T06:04:22.194945792Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | 2018/05/11 06:04:22 Validating configuration
2018-05-11T06:04:22.203457583Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | [ALERT] 130/060422 (559) : Error(s) found in configuration file : /cfg/haproxy.cfg
2018-05-11T06:04:22.203480313Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | [ALERT] 130/060422 (559) : Fatal errors found in configuration.
2018-05-11T06:04:22.203491236Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | Exit Status: 1
2018-05-11T06:04:22.203495305Z proxy_proxy.0.taen79i0mf68@swarm-manager-02    | 2018/05/11 06:04:22 Config validation failed. Will try again...
```

The Backend Directive generated by Docker Flow Proxy looks like this:
```
backend app_web-be80_0
     mode http
     http-request redirect scheme https if !{ ssl_fc }
     http-request add-header X-Forwarded-Proto https if { ssl_fc }
     server-template app_web 0 app_web:80 check resolvers docker
```

So somehow it's not recognizing the correct number of replicas. I am running 4 of the `app_web` service:
```
docker service ls
app_web                replicated          4/4                 app:latest
```

Stack File of the app_web service:

```
version: "3.5"

services:

    web:
        image: app:latest
        deploy:
            replicas: 4
            endpoint_mode: dnsrr
            labels:
                com.df.notifyProxy: 'true'
                com.df.serviceDomain: 'something.example.org'
                com.df.servicePath: "/"
                com.df.discoveryType: DNS
                com.df.srcPort.1: 443
                com.df.srcPort.2: 80
                com.df.port: 80
                com.df.httpsOnly: 'true'
            placement:
                constraints:
                    - node.labels.type == app
        networks:
            - proxy
            - database

networks:
    proxy:
        external: true
    database:
        external: true
```
