### ISSUE TITLE
Configuring multiple http ports

### ISSUE THREAD

**Issue by jonbrohauge** [docker-flow/docker-flow-proxy#24]
**Description**

Trying to configure a service to allow for proxying multiple https ports from outside the swarm.

Our proxy configuration which is pretty much out of the box
[dfp-config.yaml.txt](https://github.com/docker-flow/docker-flow-proxy/files/2089532/dfp-config.yaml.txt)

My latest shot in trying to configure multiple ports and their associated srcPort.
[wso-config.yaml.txt](https://github.com/docker-flow/docker-flow-proxy/files/2089531/wso-config.yaml.txt)

The two container called api-manager uses the following ports for different purposes:
- http port 8280 for API-REST stuff.
- https port 8243 for API-REST stuff.
- https port 9443 for GUI stuff.

Obviously we could go for a port 80 -> 8280 solution, but there is still a need for mapping two different https port to the same container. The motive behind not using 80/443 is that the above ports are the default ports used in WSO2 products, and are known in our organization. We try not to confuse our _poor developers_ by switching ports on them 😉 

I am not aware of there being different paths for the different ports, but I'll check up on it as soon as I can get a hold of one of our architects on the solution.

**Comment by thomasjpfan** [comment]
@jonbrohauge In the DFP stack, you can bind additional ports to the frontend by using the `BIND_PORTS` env variable:

```yaml
  proxy:
    image: dockerflow/docker-flow-proxy
      ...
    deploy:
       ...
    environment:
      - BIND_PORTS=8280,8243,9443
```

You can read more about `BIND_PORTS` in http://proxy.dockerflow.com/config/#environment-variables.

**Comment by jonbrohauge** [comment]
@thomasjpfan I thought that by having them listed in `ports` was exposure enough.
```yaml
proxy:
  image: ...
  ports:
    - "80:80"
    - "443:443"
    - "8280:8280"
   ...
```

**Comment by thomasjpfan** [comment]
@jonbrohauge 

1. It is correct that those ports need to be open in the DFP service. Opening the port in the proxy does **not** automatically tell DFP to listen to that port.
2. I made a mistake about where the issue in your config was. You are correct that `com.df.srcPort` (in the application service) will tell DFP to listen to that port and `BIND_PORTS` is not needed in your situation. 
3. After reviewing your application stack, I believe you are missing `com.df.servicePath: /` in your application service:

```yaml
  am-analytics:
    image: docker.wso2.com/wso2am-analytics:2.2.0
    ...
    deploy:
      labels:
        ...
        com.df.srcPort: 9444
        com.df.httpsPort: 9444
        com.df.servicePath: /
```

**Comment by jonbrohauge** [comment]
@thomasjpfan 

Is it required to use `com.df.servicePath` if I use a _non-default_ port?

In the service _am-analytics_ I do not need `com.df.servicePath` since I'm using `com.df.serviceDomain` and only (currently) have one port exposed. 

For example, this works if I use the _default_ mapping `443->9444`, i.e.:
```yaml
  am-analytics:
    image: docker.wso2.com/wso2am-analytics:2.2.0
    ...
    deploy:
      labels:
        com.df.notify: "true"
        com.df.serviceDomain: "apigw-analytics.cde.domain.local"
        com.df.httpsPort: 9444
        com.df.ignoreAuthorization: "true"
        com.df.sslVerifyNone: "true"
```

Does `com.df.srcPort` care which protocol it is serving, since there are two types of _destination ports_, `com.df.port` and `com.df.httpsPort`? My best guess is **no** because I could not find a `com.df.srcHttpsPort` to match `com.df.httpsPort` like `com.df.srcPort` matches `com.df.port`

**Comment by jonbrohauge** [comment]
@thomasjpfan I'll get on it first thing tomorrow (Europe/Copenhagen).

**Comment by thomasjpfan** [comment]
1. Gong through the source code, it doesn't look like `srcPort` is binded when constructing haproxy.cfg when using http/https. A user needs to set `BIND_PORTS` to listen to non-80,443 ports.
2. In the documentation for `srcPort` it states that `BIND_PORTS` should be used:

>  If this parameter is used with http mode, the port needs to be specified with the environment variable BIND_PORTS (see Environment Variables for more info) and the port needs to be published on service level.

This conflicts with `BIND_PORTS` documentation

>  If a port is specified with the srcPort reconfigure parameter, it is not required to specify it in this environment variable. 

@jonbrohauge I think setting `BIND_PORTS` would fix your issue. We can confirm tomorrow when the `haproxy.cfg` is obtained.

**Comment by jonbrohauge** [comment]
Without using `BIND_PORTS`:
In my _DFP_ config:
```yaml
...
    ports:
      - "80:80"
      - "443:443"
      - "8280:8280"
      - "8243:8243"
      - "9443:9443"
      - "9444:9444"
      - "9764:9764"
 ...
```
my wso2 config:
```yaml
...
    deploy:
      labels:
        com.df.notify: "true"
        com.df.serviceDomain: "apigw-analytics.cde.topdanmark.local"
        com.df.srcPort: 9444
        com.df.httpsPort: 9444
        com.df.ignoreAuthorization: "true"
        com.df.sslVerifyNone: "true"
... 
```
I continuously get: `Port query is mandatory` in my proxy-log

**Comment by jonbrohauge** [comment]
I have injected a _*.cde.topdanmark.local_ SSL certificate into the proxy-nodes as explained in http://proxy.dockerflow.com/usage/#put-certificate

**Comment by thomasjpfan** [comment]
@jonbrohauge Just to confirm what I think the issue is. Can you use the following config for DFP (no BIND_PORTS):

```
...
    ports:
      - "80:80"
      - "443:443"
      - "9444:9444"
 ...
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - TIMEOUT_SERVER=600
      - MODE=swarm
      - EXTRA_FRONTEND="bind *:9444 ssl crt-list /cfg/crt-list.txt alpn h2,http/1.1"
...
```

And test your access to http://apigw-analytics.cde.topdanmark.local:9444.

**Comment by jonbrohauge** [comment]
The log tells me to take a long walk of a short peer...
```
2018/06/13 12:34:07 Validating configuration
[ALERT] 163/123407 (48) : parsing [/cfg/haproxy.cfg:50] : Mismatched double quotes.
[ALERT] 163/123407 (48) : parsing [/cfg/haproxy.cfg:50] : unknown keyword 'bind *:9444 ssl crt-list /cfg/crt-list.txt alpn h2' in 'frontend' section
[ALERT] 163/123407 (48) : parsing [/cfg/haproxy.cfg:51] : Mismatched double quotes.
[ALERT] 163/123407 (48) : parsing [/cfg/haproxy.cfg:51] : unknown keyword 'http/1.1' in 'frontend' section
[ALERT] 163/123407 (48) : Error(s) found in configuration file : /cfg/haproxy.cfg
[ALERT] 163/123407 (48) : Fatal errors found in configuration.
Exit Status: 1
2018/06/13 12:34:07 Config validation failed. Will try again...
```

```yaml
...
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - TIMEOUT_SERVER=600
      - MODE=swarm
      - EXTRA_FRONTEND="bind *:9444 ssl crt-list /cfg/crt-list.txt alpn h2,http/1.1"
...
```

**Comment by jonbrohauge** [comment]
Did a `catV of V/cfg/haproxy.cfg`

```
frontend services
    bind *:80
    bind *:443
    mode http
    option  forwardfor
    "bind *:9444 ssl crt-list /cfg/crt-list.txt alpn h2
    http/1.1"
    acl url_cde_swarm-deploy-engine8080_0 path_beg /
```
A suspicious linefeed seems to appear...

**Comment by thomasjpfan** [comment]
The comma in `h2,http/1.1` makes this `EXTRA_FRONTEND ` hack not work.

It does look like the issue is that DFP does not have a way to configure more https ports.

**Comment by jonbrohauge** [comment]
AAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaargghhhhh!

**Comment by thomasjpfan** [comment]
I think the quickest fix to this would be to introduce a `BIND_HTTPS_PORTS` that would bind ports listening with SSL. I will put together this feature soon.

**Comment by thomasjpfan** [comment]
Actually, I am mistaken, there is a way to configure DFP to listen to non default ports on HTTPS. Can you try this in your DFP config:

...
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - TIMEOUT_SERVER=600
      - MODE=swarm
      - DEFAULT_PORTS=80,443:ssl,9444:ssl
...

**Comment by jonbrohauge** [comment]
So far, so good...
cUrl: `curl -kIv https://apigw-analytics.cde.topdanmark.local:9444/` gives a _503_ so at least the port is listening for ssl on 9444
[ha-proxy.cfg.txt](https://github.com/docker-flow/docker-flow-proxy/files/2098332/ha-proxy.cfg.txt)

Now on to configuring my application to work

Cannot test through a browser today... _Someone_ forgot to open port 9444 towards our AWS VPC.. sigh...

**Comment by thomasjpfan** [comment]
After reviewing the source code, I have a good handle on the fixes needed. I am working an updating DFP to address your issue.

**Comment by thomasjpfan** [comment]
I updated DFP with the following features:

1. Support for `com.df.httpsPort.{1,2,3,...}`.
2. Support for HTTPS without needing HTTP.
3. Adds `com.df.srcHttpsPort` to be used with `com.df.httpsPort`.

These features are in `dockerflow/docker-flow-proxy:18.06.15-62` or later.

@jonbrohauge For your use case, the services in **dfp-config** should look like:

```yaml
services:
  proxy:
    image: dockerflow/docker-flow-proxy:18.06.15-62
    ...
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - TIMEOUT_SERVER=600
      - MODE=swarm
      - BIND_PORTS=8280,8243:ssl,9443:ssl,9444:ssl

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    ...
```

The application configuration should look like:

```yaml
services:
  am-analytics:
    image: docker.wso2.com/wso2am-analytics:2.2.0
    ...
    deploy:
      labels:
        com.df.notify: "true"
        com.df.serviceDomain: "apigw-analytics.cde.domain.local"
        com.df.srcHttpsPort: 9444
        com.df.httpsPort: 9444
        com.df.ignoreAuthorization: "true"
        com.df.sslVerifyNone: "true"
      ...

  api-manager:
    image: docker.wso2.com/wso2am:2.2.0
    ...
    deploy:
      labels:
        com.df.notify: "true"
        com.df.serviceDomain.1: "apigw-manager.cde.domain.local"
        com.df.serviceDomain.2: "apigw-manager.cde.domain.local"
        com.df.serviceDomain.3: "apigw-manager.cde.domain.local"
        com.df.port.1: 8280
        com.df.httpsPort.2: 8243
        com.df.httpsPort.3: 9443
        com.df.srcPort.1: 8280
        com.df.srcHttpsPort.2: 8243
        com.df.srcHttpsPort.3: 9443
        com.df.ignoreAuthorization.2: "true"
        com.df.sslVerifyNone.2: "true"
        com.df.ignoreAuthorization.3: "true"
        com.df.sslVerifyNone.3: "true"
      ...
```

There may still be bugs to be ironed out. Let me know how it goes!
