### ISSUE TITLE
Feature: Allow canary deployments

### ISSUE THREAD

**Issue by rubensyltek** [docker-flow/docker-flow-proxy#34]
It would be great if docker-flow-proxy allows canary deployments. 

Let's say we deploy two versions of the same service, mapped with the same docker-flow-proxy configuration. It would be great if the HAProxy is configured to redirect traffic to both versions of the application. Currently, as far as I've been able to test, that's not the case.

With a docker-compose file like this one:

```yml
version: '3.5'

services:
  canary:
    build:
      context: .
      dockerfile: Dockerfile
    image: canary:0.1.0
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/canary
        - com.df.port=8080
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
    networks:
      - proxy
      - service
  canaryV2:
      build:
        context: .
        dockerfile: Dockerfile
      image: canary:0.2.0
      deploy:
        labels:
          - com.df.notify=true
          - com.df.distribute=true
          - com.df.servicePath=/canary
          - com.df.port=8080
        replicas: 2
        update_config:
          parallelism: 1
          failure_action: rollback
      networks:
        - proxy
        - service
networks:
  proxy:
    external: true
  service:
    external: true
```

The only version that gets traffic is Version 1. First approach would be to redirect traffic in a round-robin way. Most advanced scenarios would be to use request headers to identify what traffic goes to which version of the service.

Let me know if I can help with this feature.

**Comment by thomasjpfan** [comment]
There is a `serviceGroup` feature when using tcp mode. The services with the same `com.df.ServiceGroup` label would follow the balance mode `com.df.balanceGroup` to distribute requests. 

DFP really likes to assume "one service = one frontend" and "one service can have multiple backends corresponding to different `com.df.servicePath.*` labels". This is held strongly by how DFP internally stores the services. This assumption was not held too strongly for TCP mode, thus the `serviceGroup` feature was added to it. (It uses haproxy's listen instead of a pair of frontend and backends)

For this feature to be added into HTTP, the following would also need to work:

```yaml
services:
  canary:
    image: canary:0.1.0
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceGroup=canaryGroup
        - com.df.servicePath=/canary
        - com.df.balanceGroup=leastconn
        - com.df.port=8080
  canaryV2:
      image: canary:0.2.0
      deploy:
        labels:
          - com.df.notify=true
          - com.df.distribute=true
          - com.df.servicePath.1=/endpoint
          - com.df.port.1=8081
          - com.df.serviceGroup.2=canaryGroup
          - com.df.servicePath.2=/canary
          - com.df.balanceGroup.2=leastconn
          - com.df.port.2=8080
```

In the current version of DFP this would produce a haproxy config similar to:

```
frontend services
    bind *:80
    acl url_canary8080_0 path_beg /canary
    acl url_canaryV28081_1 path_beg /endpoint
    acl url_canaryV28080_2 path_beg /canary
    use_backend canary-be8080_0 if url_canary8080_0
    use_backend canaryV2-be8081_1 if url_canaryV28081_1
    use_backend canaryV2-be8080_2 if url_canaryV28080_2

backend canary-be8080
    server canary_0 canary:8080

backend canaryV2-be8081_1
    server canaryV2_1 canaryV2:8081

backend canaryV2-be8080_2 
    server canaryV2_2 canaryV2:8080
```

Notice how the canary-be8080 is first, so it gets all the `/canary` traffic.

To enable the grouping feature, we would need `/endpoint` to direct requests to `canaryV2`, and `/canary` to distribute requests between the two services with `balance leastconn` in haproxy. If we add `serviceGroup` and `balanceGroup` to HTTP mode, DFP would store the internal state that looks like this (simplify to json):

```json
[
    {"service": "canary",
     "serviceDest": [
        {
            "serviceGroup": "canaryGroup",
            "servicePath": "/canary",
            "balanceGroup": "leastconn",
            "port": 8080
        }
    ]},
    {"service": "canaryV2",
     "serviceDest": [
        {
            "servicePath": "/endpoint",
            "port": 8081
        },
        {
            "serviceGroup": "canaryGroup",
            "servicePath": "/canary",
            "balanceGroup": "leastconn",
            "port": 8080
        }
    ]}
]
```

This would need to converted to a haproxy config that looks like:

```
frontend services
    bind *:80
    acl url_canaryV28081_1 path_beg /endpoint
    acl url_canaryGroup8080 path_beg /canary
    use_backend canaryGroup-be8080 if url_canaryGroup8080
    use_backend canaryV2-be8081_1 if url_canaryV28081_1

backend canaryGroup-be8080
    balance leastconn
    server canaryV2_2 canaryV2:8080
    server canary_0 canary:8080

backend canaryV2-be8081_1
    server canaryV2_1 canaryV2:8081
```

There is also https to consider. The major change is to get 

https://github.com/docker-flow/docker-flow-proxy/blob/8437e0581ccf5fb533d4df7696f5c5b8b00e16a8/proxy/template.go#L12

and
