### ISSUE TITLE
Registered Service Path returns a 404 for no auth based service and 401 for auth based service.

### ISSUE THREAD

**Issue by pranshuverma** [docker-flow/docker-flow-proxy#41]
**Description**

Following http://proxy.dockerflow.com/swarm-mode-stack/ process to setup docker-flow-proxy stack. The stack is up and running and listening and registering new services. But except for the test service mentioned in doc all others services I deploy get registered but on trying the servicePath URL I get a 404 response for 

**Steps to reproduce the issue:**
1. For no auth based service - Try deploying a basic consul cluster using deploy stack. The service works using the endpoint exposed. Labels used are
```
labels:
        - com.df.notify=true
        - com.df.servicePath=/consul
        - com.df.port=8500
```

2. For auth based service - I am deploying swarmpit. Labels used are 
```
labels:
        - com.df.notify=true
        - com.df.servicePath=/swarmpit
        - com.df.users=admin:admin
        - com.df.port=8080
```
Assuming com.df.users help me provide the users for login to mapped service.

**Describe the results you received:**
* No auth based service logs on enabling debug on docker-flow-proxy are below:
```
df_proxy.0.aofchyt7vl1i@host1    | 2018/07/19 07:59:26 HAPRoxy: 10.0.86.152:46180 [19/Jul/2018:07:59:26.800] services sd_server-be8500_0/sd_server 0/0/1/1/2 404 82 - - ---- 2/2/0/1/0 0/0 "GET /consul HTTP/1.1"
df_proxy.0.aofchyt7vl1i@host1    | 2018/07/19 07:59:31 HAPRoxy: 10.0.86.152:46182 [19/Jul/2018:07:59:26.586] services services/<NOSRV> -1/-1/-1/-1/5000 408 666 - - cR-- 2/2/0/0/0 0/0 "<BADREQ>"
```
* Auth based service logs on enabling debug on docker-flow-proxy are below:
```
df_proxy.0.aofchyt7vl1i@host1    | 2018/07/19 08:01:04 HAPRoxy: 10.0.86.152:46258 [19/Jul/2018:08:01:04.302] services sp_app-be8080_0/<NOSRV> -1/-1/-1/-1/0 401 255 - - PR-- 1/1/0/0/3 0/0 "GET /swarmpit HTTP/1.1"
df_proxy.0.aofchyt7vl1i@host1    | 2018/07/19 08:01:10 HAPRoxy: 10.0.86.152:46260 [19/Jul/2018:08:01:10.902] services sp_app-be8080_0/sp_app 0/0/0/20/20 401 307 - - ---- 1/1/0/1/0 0/0 "GET /swarmpit HTTP/1.1"
df_proxy.0.aofchyt7vl1i@host1    | 2018/07/19 08:01:11 HAPRoxy: 10.0.86.152:46260 [19/Jul/2018:08:01:11.159] services services/<NOSRV> -1/-1/-1/-1/0 503 674 - - SC-- 1/1/0/0/0 0/0 "GET /favicon.ico HTTP/1.1"
```

**Describe the results you expected:**
The urls should show me the services.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is always happening, however I am able to access service using host exposed ports.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical VMs.

**Comment by thomasjpfan** [comment]
Can you provide the stack file for the consul service?

**Comment by pranshuverma** [comment]
@thomasjpfan 
```
---
version: '3.6'
networks:
  default:
    external:
      name: main
  proxy:
    external:
      name: main-proxy

services:
  # Deploy the consul server instances
  server:
    image: consul:1.2.0
    networks:
      default:
        aliases:
          - consul.server
          - "{{.Service.Name}}"
      proxy:
        aliases:
          - consul.server
          - "{{.Service.Name}}"

    # Start the consul server with the given configuration
    command: "consul agent -config-file /consul/config/config.json"

    # Expose port 8500 so we can access the UI and allow connections across datacenters.
    ports:
      - target: 8500
        published: 8500
        mode: host

    # Mount the configuration and data volumes to the container.
    volumes:
      - /ha-tools/consul:/consul/config:rw
      - /ha-tools/consul/data:/consul/data:rw

    # Deploy the consul server on all servers which are managers.
    # Use DNS Round Robin instead VIP for discovery. This ensures we get all running
    # consul server instances when querying consul.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
      labels:
        - com.df.notify=true
        - com.df.servicePath=/consul
        - com.df.port=8500

    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    # container_name: "{{.Service.Name}}-{{.Task.Slot}}"

  # Deploy the consul agent instances
  agent:
    image: consul:1.2.0
    networks:
      default:
        aliases:
          - consul.agent
          - "{{.Service.Name}}"

    # Start the consul agent with the given configuration
    command: "consul agent -config-file /consul/config/config.json"

    # Expose port 8500 so we can access the UI and allow connections across datacenters.
    ports:
      - target: 8500
        published: 8500
        mode: host

    # Mount the configuration and data volumes to the container.
    volumes:
      - /ha-tools/consul:/consul/config:rw
      - /ha-tools/consul/data:/consul/data:rw

    # Deploy the consul agent on all servers which are workers.
    # Use DNS Round Robin instead VIP for discovery.
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker

    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    # container_name: "{{.Service.Name}}-{{.Task.Slot}}"
```
