### ISSUE TITLE
Rollback in docker swarm no being re-registered?

### ISSUE THREAD

**Issue by drozzy** [docker-flow/docker-flow-proxy#64]
Is anyone else getting weird behaviour, where if docker swarm (mode) performs a rollback automatically, then the old (rolled back to) version is not registered in proxy?

Thanks.

**Comment by thomasjpfan** [comment]
This sounds like a bug in DFSL. Currently, DFSL does not consider the image tag when determining if a service has been changed.

**Comment by drozzy** [comment]
Yea, if I have a stack file, defined like this (`$tag` here is unique per commit):

```
version: "3.6"

services:

  myapp:
    image: $image:$tag
    deploy:
      placement:
        constraints: 
          - node.role == worker
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
```

So if I deploy a bad version of the service, and the docker swarm takes over and rolls-back the service, it seems like the proxy is not longer proxying correctly.

Doing `docker stack rm` and then deploying again makes it work.
