### ISSUE TITLE
Docker Flow Proxy doesn't listen to service removals

### ISSUE THREAD

**Issue by jaschaio** [docker-flow/docker-flow-proxy#8]
If I create a service and later remove it docker flow proxy gets stuck into a reconfiguration loop.

This might be related to https://github.com/vfarcic/docker-flow-proxy/issues/453 although it seems that this is not caused by the rapid creation and removal of services but just at any time when I remove a docker flow proxy labeled service with `docker service rm service_name`.

Docker Flog Proxy Logs:
```
proxy_proxy.1.lcn2oedr07ly@Docker-Manager    | 2018/04/19 12:24:08 Validating configuration
proxy_proxy.1.lcn2oedr07ly@Docker-Manager    | [ALERT] 108/122408 (208) : parsing [/cfg/haproxy.cfg:106] : 'server app_u0oy5r45p775' : could not resolve address 'app_u0oy5r45p775'.
proxy_proxy.1.lcn2oedr07ly@Docker-Manager    | [ALERT] 108/122408 (208) : Failed to initialize server(s) addr.
proxy_proxy.1.lcn2oedr07ly@Docker-Manager    | Exit Status: 1
proxy_proxy.1.lcn2oedr07ly@Docker-Manager    | 2018/04/19 12:24:08 Config validation failed. Will try again...
```

Docker Flow Swarm Listener Logs:
```
proxy_swarm-listener.1.r1hsv1vbaayp@Docker-Manager    | 2018/04/19 12:23:22 Sending service removed notification to http://proxy:8080/v1/docker-flow-proxy/remove?distribute=true&serviceName=app_u0oy5r45p775
proxy_swarm-listener.1.r1hsv1vbaayp@Docker-Manager    | 2018/04/19 12:23:22 Canceling service remove notification to http://proxy:8080/v1/docker-flow-proxy/remove?distribute=true&serviceName=app_u0oy5r45p775
```

Using `dockerflow/docker-flow-proxy:18.04.18-37` and `dockerflow/docker-flow-swarm-listener:18.04.15-5`

**Comment by jaschaio** [comment]
I tried with `vfarcic/docker-flow-swarm-listener:18.03.25-41` and it works. So this is probably a bug in a recent release. @vfarcic Not sure if it's possible to make the previous tags as well available on the fork so that there is no need to switch between `vfarcic` and `dockerflow` on docker hub.

**Comment by thomasjpfan** [comment]
Something is causing DFSL to cancel the remove notification. I was unable to reproduce the issue with the following:

```bash
git clone https://github.com/docker-flow/docker-flow-proxy
docker stack deploy -c docker-compose-stack.yml proxy
docker service create --name test -d \
  -l com.df.notify=true --mode global \
  -l com.df.servicePath=/test \
  -l com.df.port=80 \
  --network proxy emilevauge/whoami
docker service rm test
```

Can you provide a sample stack file and steps to reproduce this issue?

**Comment by jaschaio** [comment]
I have since set up a new cluster and couldn't reproduce the issue.

**Comment by jaschaio** [comment]
Sorry for the late reply, I thought that I had it resolved when I changed to a different cluster but I was wrong.

This is the stack that doesn't work for me:

```
version: "3.5"

services:

    proxy:
        image: dockerflow/docker-flow-proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - proxy
        environment:
            - LISTENER_ADDRESS=proxy_swarm-listener
            - SERVICE_NAME=proxy_proxy
            - MODE=swarm
        deploy:
            placement:
                constraints:
                    - node.role == manager

    letsencrypt:
        image: nib0r/docker-flow-proxy-letsencrypt
        networks:
            - proxy
        environment:
            - DF_PROXY_SERVICE_NAME=proxy_proxy
            - DF_SWARM_LISTENER_SERVICE_NAME=proxy_swarm-listener
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            labels:
                - com.df.notify=true
                - com.df.servicePath=/.well-known/acme-challenge
                - com.df.port=8080
            placement:
                constraints:
                    - node.role == manager

    swarm-listener:
        image: dockerflow/docker-flow-swarm-listener
        networks:
            - proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy_letsencrypt:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
            - DF_RETRY_INTERVAL=5
        deploy:
            placement:
                constraints:
                    - node.role == manager

networks:
    proxy:
        external: true
```

If I remove the `letsencrypt` service from the stack file it does seem to work. I only get the `Canceling service remove notification` when I try to run it together with the letsencrypt service. This might be a bug in [`docker-flow-proxy-letsencrypt`](https://github.com/n1b0r/docker-flow-proxy-letsencrypt) but it still confuses me that it is the `docker-flow-swarm-listener` who is canceling the notification.

Maybe its due to using two different url's for `DF_NOTIFY_REMOVE_SERVICE_URL` and `DF_NOTIFY_CREATE_SERVICE_URL`?
