### ISSUE TITLE
Feature: Add restriction of client src IPs

### ISSUE THREAD

**Issue by aisbergg** [docker-flow/docker-flow-proxy#84]
A nice feature would be the possibility to restrict the access to certain services (e.g. admin interfaces) to certain client src IPs. I would like restrict some adminstration services to only be available when accessed by Local IP.

So using labels on the specific containers like:
```yaml
services:
  phpmyadmin:
    ...
    deploy:
      labels:
        # restrict access from clients via IP
        - com.df.allowedSrc=10.0.0.0/16 172.16.0.0/12
        # restrict access from clients via port
        - com.df.allowedSrcPort=0:1023
```

should result in haproxy.cfg like:
```
acl allowedSrc_global_phpmyadmin8080_0 src 10.0.0.0/16 172.16.0.0/12
acl allowedSrcPort_global_phpmyadmin8080_0_port src_port 0:1023
use_backend global_phpmyadmin-be8080_0 if ... allowedSrc_global_phpmyadmin8080_0 allowedSrcPort_global_phpmyadmin8080_0
```
