### ISSUE TITLE
routing non HTML traffic

### ISSUE THREAD

**Issue by lukicsl** [docker-flow/docker-flow-proxy#91]
I am running openhab inside the swarm.
Managed to get it running.
Stuck right now with missing option/knowledge how to route none html traffic from outside to openhab service.
proxy should listen to ports 9125, 9126 and route to the service.

```
version: "3"

services:

  openhab:
    image: openhab/openhab:2.4.0
    container_name: openhab
    networks:
      - monitor
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab/openhab_addons:/openhab/addons \
      - /datavol/openhab/openhab_conf:/openhab/conf \
      - /datavol/openhab/openhab_userdata:/openhab/userdata 
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/openhab,/rest,/start,/habpanel,/habmin,/doc,/paperui
        - com.df.reqPathSearchReplace=/openhab,/
        - com.df.port=8080
  
  frontail:
    image: lukics/frontail:linux-arm32v7-latest
    networks:
      - monitor
      - proxy
    volumes:
      - /datavol/openhab/openhab_userdata:/openhab/userdata
    command:
      - --url-path /oh-log
      - /openhab/userdata/logs/events.log  
      - /openhab/userdata/logs/openhab.log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/oh-log
        - com.df.port=9001


networks:
  monitor:
    external: true
  proxy:
    external: true  
```
with HAProxy that should be manageable:
[https://www.linickx.com/load-balance-anything-with-haproxy](https://www.linickx.com/load-balance-anything-with-haproxy)

**Comment by thomasjpfan** [comment]
What kind of traffic are you proxying? TCP?

**Comment by lukicsl** [comment]
yes,
in principle it is some sort of json, xml and binary rpc data

**Comment by thomasjpfan** [comment]
Are you only proxying TCP traffic?

**Comment by lukicsl** [comment]
yes,

I finally foud the tcp support option, but seems not work as I expect.

I am having this service definition:
 ```
       - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/openhab,/rest,/start,/habpanel,/habmin,/doc,/paperui
        - com.df.reqPathSearchReplace.1=/openhab,/
        - com.df.port.1=8080
        - com.df.servicePath.2=/
        - com.df.srcPort.2=9125
        - com.df.port.2=9125
        - com.df.reqMode2=tcp
        - com.df.servicePath.3=/
        - com.df.srcPort.3=9126
        - com.df.port.3=9126
        - com.df.reqMode3=tcp

```

but somehow the result is:
```
proxy_proxy.1.k33rhpamkhil@vevedock-02    | backend openhab_openhab-be8080_1
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     mode http
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     http-request set-path %!
proxy_proxy.1.k33rhpamkhil@vevedock-02    | (BADINDEX)    server openhab_openhab openhab_openhab:8080
proxy_proxy.1.k33rhpamkhil@vevedock-02    | backend openhab_openhab-be9125_2
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     mode http
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     server openhab_openhab openhab_openhab:9125
proxy_proxy.1.k33rhpamkhil@vevedock-02    | backend openhab_openhab-be9126_3
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     mode http
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     http-request add-header X-Forwarded-Proto https if { ssl_fc }
proxy_proxy.1.k33rhpamkhil@vevedock-02    |     server openhab_openhab openhab_openhab:9126
proxy_proxy.1.k33rhpamkhil@vevedock-02    | 2019/01/14 15:15:32 Proxy config was reloaded
proxy_proxy.1.k33rhpamkhil@vevedock-02    | 2019/01/14 15:15:32 Reloading the proxy
proxy_proxy.1.k33rhpamkhil@vevedock-02    | 2019/01/14 15:15:32 Validating configuration
proxy_proxy.1.k33rhpamkhil@vevedock-02    | Configuration file is valid
proxy_proxy.1.k33rhpamkhil@vevedock-02    | 2019/01/14 15:15:33 Proxy config was reloaded

```

**Comment by lukicsl** [comment]
The proxy setting is:
```
    ports:
      - 80:80
      - 443:443
      - 9125:9125
      - 9126:9126
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=${CONNECTION_MODE:-http-server-close}
      - STATS_USER=admin
      - STATS_PASS=admin
      - BIND_PORTS=9125,9126
```
