### ISSUE TITLE
Possibility to override the name when sticky-server is enable

### ISSUE THREAD

**Issue by T1loc** [docker-flow/docker-flow-proxy#97]
**Description**
I would like to be able to set the cookie name when I enable the sticky-server.
The service name should not be used as the cookie name.

```
version: '3'

services:
  web:
    image: "nginx"
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=demo.org
        - com.df.port=80
        - com.df.httpsOnly=true
        - com.df.sessionType=sticky-server
        - com.df.cookieName=HA
```
